CC := gcc
CFLAGS := -O3 -msse -Wall -Wextra
TARGET := test_simd
SRC := mat_multi.c

.PHONY: all clean run

all: $(TARGET)

$(TARGET): $(SRC)
    $(CC) $(CFLAGS) -o $@ $^

clean:
    rm -f $(TARGET)

run: $(TARGET)
    ./$(TARGET)